### ISSUE TITLE
How to config this extension to use all venv folder of automatic 1111

### ISSUE THREAD

**Issue by wardensc2** [ModelSurge/sd-webui-comfyui#102]
Hi ModelSurge

After install ComfyUI manager I manager to install missing node however some node require some module in the venv folder such as numba module etc... 

The WebUI has all the modules but I dont know to config the extension  to find in the venv folder

Please help, thank in advance

**Comment by John-WL** [comment]
Hi, 

Right now, ComfyUI should be launching from the Webui itself aytomatically when using the extension. This means that ComfyUI should be using the same venv as the Webui when it is being launched from the extension. 

Therefore, I am not sure how to help, as the problem is probably not that ComfyUI needs to be set up to use the same venv as the Webui. 

Do you have any error traces? That could help, if you have any. 

For your info, we are working on separating the processes completely to allow using different venvs (or continue sharing them if the user wishes to). I don't know if this info could help you solve your issue or not though.

**Comment by wardensc2** [comment]
Here is my error when run Comfy with the workflow due to A1111 console only show A1111 running, I cant see any error report with ComfyUI running inside A1111.

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/77379748/04e3977c-bda7-41fd-8819-7665b4e39b30)

This problem can be fixed if I use ComfyUI directly by copy the missing modules from python folder to ComfyUI venv folder

But when using ComfyUI extension inside A1111 the venv folder inside ComfyUI doesn't existed

**Comment by John-WL** [comment]
ComfyUI that is launched from the extension should be using the same venv as the Webui. So, if you want to copy-paste modules across venvs, you would need to add the missing files to the Webui venv directly right now. 

Of course, for adding the proper libraries and dependancies, using pip directly is always recommended instead of adding files manually across venvs. 

I don't know about these nodes, but it seems to me like maybe the python files for these custom nodes might not be present in the ComfyUI folder. You might want to double check in the `ComfyUI/custom_nodes` folder and see if the nodes are really there.

**Comment by ljleb** [comment]
Closing this as no response from OP. In any case, we are planning to add a setting to chose whether to use the ComfyUI venv or the webui venv, so this shouldn't be a problem anymore in the near future.
