### ISSUE TITLE
loading stopped, what's the matter with it

### ISSUE THREAD

**Issue by jasoncow007** [ModelSurge/sd-webui-comfyui#157]
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints D:\sd-webui-aki-v4\models/Stable-diffusion
Adding extra search path configs D:\sd-webui-aki-v4\models/Stable-diffusion
Adding extra search path vae D:\sd-webui-aki-v4\models/VAE
Adding extra search path loras D:\sd-webui-aki-v4\models/Lora
Adding extra search path loras D:\sd-webui-aki-v4\models/LyCORIS
Adding extra search path upscale_models D:\sd-webui-aki-v4\models/ESRGAN
Adding extra search path upscale_models D:\sd-webui-aki-v4\models/RealESRGAN
Adding extra search path upscale_models D:\sd-webui-aki-v4\models/SwinIR
Adding extra search path embeddings D:\sd-webui-aki-v4\embeddings
Adding extra search path hypernetworks D:\sd-webui-aki-v4\models/hypernetworks
Adding extra search path controlnet D:\sd-webui-aki-v4\models/ControlNet
### ComfyUI Revision: 1399 [2419901e]

**Comment by ljleb** [comment]
The issue is really unclear as there's only logs and no explanation.

If you are running into a situation where the comfyui server freezes before finishing to start, I just tested on my side, and on I'm not able to reproduce on the latest version of the webui, the latest version of the extension and the latest version of comfyui.

If you could provide more information, for example your operating system, and the version of the webui and sd-webui-comfyui you are using, it could help me or someone else narrow it down.
