### ISSUE TITLE
comfiui blank screen error

### ISSUE THREAD

**Issue by jejejejajaja** [ModelSurge/sd-webui-comfyui#208]
I think ai it self is running fine, but comfyui screen does not show anything. does anyone know what is supposed to be the problem?

**Comment by ljleb** [comment]
related to #184, let us know if this is the same situation.

**Comment by jejejejajaja** [comment]
I can't acually understand what that situation is. 
My cmd prompt shows like this.
`
C:\Users\bvlon\Downloads\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 6144 MB, total RAM 16315 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1660 SUPER : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
`

and my internet browser(chrome and also same with edge) looks like this.
![캡처](https://github.com/ModelSurge/sd-webui-comfyui/assets/157805055/6fd7dd17-d682-41a6-8ad1-8920957a9c54)
I also did the same job at my another computer, and it works. so i think my installation process isn't wrong.

**Comment by ljleb** [comment]
This repository is an extension to [stable diffusion webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui) that downloads and loads [comfyui](https://github.com/comfyanonymous/ComfyUI) and connects it to the host UI. It is not comfyui itself. IIUC, this problem is unrelated to this repository. If that is the case, please close this and reopen an issue in comfyui, if there isn't one already open related to the problem you are running into.

**Comment by jejejejajaja** [comment]
oh then this repository cannot help.. ok thank you so much

**Comment by jejejejajaja** [comment]
I tried this extention too and it does not work either.. only blank screen shows.
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/157805055/0a34d8ea-fc16-40a3-b83f-fb2042ffa785)
and here
![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/157805055/8ae3df8d-3b59-43ea-ba36-ce4920352da9)


comfy ui extention and comfyui itself both does not work.(I also opened the issue on comfyui repository)

**Comment by ljleb** [comment]
The issue seems to be on the side of comfyui. If comfyui does not work on its own, then this extension won't be able to make it work either.

I will close for now, but please let us know here or in a new issue if more information comes up that indicates the extension may play a role in a related problem.
