### ISSUE TITLE
Checkpoints aren't shared

### ISSUE THREAD

**Issue by John-WL** [ModelSurge/sd-webui-comfyui#5]
Would be nice to have a node "WebuiCheckpointLoader" that can use the checkpoint that's already in memory.

**Comment by ljleb** [comment]
We have the node but it does not reuse the memory. Pickle not happy because it tries to unpickle the model in a different environment. It also is very unhappy about the circular dependencies in the webui (`sd_hijack`). Needs more investigation.

**Comment by ljleb** [comment]
Maybe a workaround for this could be to just make a button to unload the webui models and/or the comfyui models.

**Comment by John-WL** [comment]
that's not the same feature, and would be more of a hindrance than anything in my opinion, as it can take a while to load a model

**Comment by ljleb** [comment]
I agree it's not the best, but it would allow to use the extension on systems with less resources. not a peefect solution, just a workaround since there does not seem to be a good solution so far. There's a lazy-loading PR in the a1111 webui repo, I was thinking maybe there's a way to revert the state back to lazy-loaded if you want to save some memory.

**Comment by John-WL** [comment]
I think this should be labeled as another feature, then, as this feature is meant to "share" checkpoints for convenience as well. 

I can see how it would be useful for some users, and it would probably be easier to do, and I think it's a great idea. 

Being able to share the models would remove the need for this extra feature, though, so maybe it would be better to focus on that directly instead.

**Comment by ljleb** [comment]
Time is money. Let's at least have some way of mitigating this, and when we have a solution here we can remove the code if it is not needed anymore.

**Comment by John-WL** [comment]
Feel free to make a pr, I'll review it. As I said, I think this is not exactly the same feature, so I wouldn't close this issue even if you can disable models

**Comment by ronmurphy** [comment]
see this video, link shell extension, windows only thought, although in linux you could use a shell links also.

https://www.youtube.com/watch?v=V4oEY4Y44Ws

**Comment by John-WL** [comment]
If I understand correctly, this is basically a simlink, but the problem is much deeper. If you want to use both the webui and ComfyUI at the same time, it essentially costs twice as much memory (broadly speaking). The idea is to use the same model in ram and vram memory, not juste hard drive memory (which, as you mentionned, is a non-issue).

**Comment by ljleb** [comment]
> The codebase and libraries for both types of models are very similar. In fact, the model objects that ComfyUI needs seem to be a subset of what the webui needs. Thing is, there are some small differences that make it tricky to get them working correctly in sinc.

This, but also while trying to do this we realized this would not work because pickle does not want to work with the recursive imports of the webui (this code base needs a serious refactor, but it would possibly break a lot of extensions so we can't really explore this path I think). Then, when we try to use the same process for both, well comfyui ends up with a completely different ldm module (the webui one) and so some discrepancies in the implementation details make the code raise errors a little bit everywhere.

We need to be able to reuse the process while replacing global package dependencies like `sys` and `ldm` with the right values, but only in the comfyui thread. So far we achieved this by using a different process for comfyui, making it possible to override the important values (namely `sys.args` and add the comfyui directory to `sys.path`) but I am not sure there is a way to do this within the same process (whether in a different thread or not).

One solution could be to clone comfyui and patch the code to not depend directly on these globals but instead depend on proxy variables that can be modified as needed without also modifying these values for the webui.

**Comment by zethfoxster** [comment]
you could add settings in the auto1111 settings tab that allows us to set the directories ourselves rather than hardcoded paths in the .py

**Comment by John-WL** [comment]
If I recall correctly, there's a yaml config file that comfyui loads on startup to check where the models are. Is there a reason to have an additional UI element for models location rather than setting up this yaml file?

**Comment by zethfoxster** [comment]
encapsulation of the project, Im coming to comfyui with no prior knowledge of the yaml set up...meaning all I know is this extension version where there is no mention of a yaml file that could be set up. 
I ended up doing symlinks to all my model folders, so personally it wont effect me in the least, I simply made the suggestion as it would be cleaner to treat this extension as a standalone of the original imo.
I don't bother reading a single thing about auto1111 as a vladauto1111 user, I have a feeling comfy extension users wont be going to the original to read a thing either.

**Comment by John-WL** [comment]
Ah, I think you're right, it would be nice to have a models location setting in the settings, as comfyui doesn't allow to select the models through the command line (to my knowledge). I'll create an issue for selecting the models in the settings. 

This would mainly involve setting up the yaml file automatically in the linked comfyui directory, so probably very easy to do.

**Comment by ljleb** [comment]
One way to tackle this would be to serialize and unload the currently loaded sd model in the webui. This would make the extension work with the in-memory merge feature of supermerger, at the cost of speed.

**Comment by ljleb** [comment]
Wait but since we are using a thread ATM, maybe we can just share the state dict directly?

**Comment by John-WL** [comment]
I thought that's what we tried

**Comment by ljleb** [comment]
I don't think we tried sending the entire state dict. we tried sending the loaded model itself

**Comment by John-WL** [comment]
We implemented the `Webui Checkpoint Loader` node. For now, the node is duplicating the data in-memory, but at least people can use it directly.
