### ISSUE TITLE
TAESD(xl) previews failure

### ISSUE THREAD

**Issue by EriIaz** [ModelSurge/sd-webui-comfyui#60]
I've run into an issue: the TAESD previews stopped working after connecting ComfyUI as a plugin, both as A1111 plugin and standalone. The standalone configuration wasn't changed, and I don't remember updating it.
Chances are, the first run messed up something in my venv. There were no errors, but I saw the startup was odd and it was installing some libraries. Please, don't do that. The plugin shouldn't change ANYTHING in an existing installation unless it's absolutely essential for the extension's function.

**Comment by ljleb** [comment]
The extension does not explicitly install anything in the venv, but comfyui may be responsible for this. Comfyui seems to be able to work with the venv of other repos according to their readme: https://github.com/comfyanonymous/ComfyUI#i-already-have-another-ui-for-stable-diffusion-installed-do-i-really-have-to-install-all-of-these-dependencies

Which is why I thought it wouldn't create issues to set it up like that. To launch comfyui in its own isolated venv, we may have to first fix the WebuiCheckpointLoader node so that it doesn't need to copy the entire state dict between the two processes.

Another quick but dirty solution would be to explicitly serialize and deserialize the state dict, which would be slower and will take even more memory.

Once this is done, we could replace runpy with a subprocess to launch comfyui.

**Comment by ljleb** [comment]
Unfortunately I'm unable to reproduce the issue. Did you install multiple extensions simultaneously, or you are certain this is caused by this extension?

**Comment by John-WL** [comment]
TAESD works fine with or without the extension on my side. Like @ljleb said, we do not explicitely install any additional dependencies other than the ComfyUI repo itself if the user presses a button.

**Comment by John-WL** [comment]
The most likely case is that this is a problem with ComfyUI itself when using the same venv, not directly with this extension. I think this issue should be moved to the official ComfyUI repo.

**Comment by EriIaz** [comment]
Okay, it seems I've found the cause of this issue and fixed it with a dirty hack.

Turns out, the plugin somehow reconfigured the standalone instance of my ComfyUI to use A1111's venv.
And something in this venv conflicts with ComfyUI's TAESD implementation. I didn't find the exact file that was changed since I wasn't even considering shared venv precisely because of this issue, but I managed to fall back to the ComfyUI's own venv by temporarily renaming the venv folder in A1111, making it seemingly nonexistent.

**Comment by ljleb** [comment]
How do you start comfyui usually? Whether you start comfyui or a1111 webui, you need to first activate a venv. How is this venv activated? IIUC, the extension cannot be directly responsible for which venv you activate before running one or the other.

**Comment by ljleb** [comment]
Whether you start comfyui or a1111 webui, you need to first activate a venv. How is this venv activated on your setup? IIUC, the extension cannot be directly responsible for which venv is activated before running one or the other as the main script. It *will* use the a1111 webui venv when starting comfyui from the extension, but otherwise it should be completely up to you which venv is used to start a python program.

**Comment by ljleb** [comment]
Closing this as no response from OP. Please @EriIaz reopen the issue with a description of how comfyui is started on your system if there is still an issue, so we can determine whether any part of the code needs to be fixed.
