### ISSUE TITLE
How to config the Comfy to make automatic 1111 redirect to workflow to Comfy (gif file tutorial very difficult to follow)

### ISSUE THREAD

**Issue by wardensc2** [ModelSurge/sd-webui-comfyui#94]
I try to copy the work to redirect A1111 to Comfy but the gif missing the information which making this process not work, please provide us a clearer workflow. Thank you so much

![image](https://github.com/ModelSurge/sd-webui-comfyui/assets/77379748/97bcb5f2-47e6-4dc5-865b-50ec35eaf4a6)

**Comment by John-WL** [comment]
Hi, please read the wiki in the "Webui Nodes" section for all the info on how to use ComfyUI for workflow types. 

The workflow shown in the readme is just an example of what's possible, but sky is the limit for what's possible. 

First, the webui generates an image normally. Then, the image is being fed through the "Postprocess From Webui" nodes. 

In order to send the postprocessed image(s) back to the webui, you can wire final images to "Postprocess To Webui" nodes. 

Let us know if you have more questions about this or if you have suggestions to improve the wiki :)

**Comment by ljleb** [comment]
I believe all the information you could need is displayed on the image, so I am not sure which information you want us to provide you with.

If you are trying to reproduce the readme example, you should be able to drag and drop this json file into the comfyui postprocess window:
https://gist.githubusercontent.com/ljleb/e96e53734db7601f8e6de443c31e1a91/raw/937ab8fa620d56ad2ccf5eb9db58cd34b64b5f37/front-page-workflow.json

Hope this helps reproduce the workflow.
